[build]
  functions = "netlify/functions"
  publish = "build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

[build.environment]
  NODE_VERSION = "18"
